package com.test.loan_sample.loan_sample;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Loan implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Loan() {
    }

}